/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DwarvenForgeEastAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DwarvenForgeEastAddonDeed();
			}
		}

		[ Constructable ]
		public DwarvenForgeEastAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 6546 );
			ac.Name = "Dwarven Forge";
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6554 );
			ac.Name = "Dwarven Forge";
			AddComponent( ac, 0, 0, 0 );
		}

		public DwarvenForgeEastAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DwarvenForgeEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DwarvenForgeEastAddon();
			}
		}

		[Constructable]
		public DwarvenForgeEastAddonDeed()
		{
			Name = "Dwarven Forge East";
		}

		public DwarvenForgeEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}